# Generated by Django 3.2.2 on 2021-05-13 10:14

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='defaults/1.jpg', null=True, upload_to=user.models.upload_cover_to),
        ),
    ]
